CREATE TABLE IF NOT EXISTS flight (
  id INT primary key generated by default as identity,
  flight_number VARCHAR(15),
  airline VARCHAR(100),
  departure_city VARCHAR(100),
  destination_city VARCHAR(100),
  departure_time TIMESTAMP,
  arrival_time TIMESTAMP,
  flight_distance INT,
  price FLOAT
);